// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-TwTtVkDttO8o4Vr1xibPXkAKUZF1bKM',
    appId: '1:270620624991:web:54211a7374b12286e333ea',
    messagingSenderId: '270620624991',
    projectId: 'login-c2782',
    authDomain: 'login-c2782.firebaseapp.com',
    storageBucket: 'login-c2782.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqt0NkmzlulGqEwmQhBpc04ibW76hb-o0',
    appId: '1:270620624991:android:13040fb2a10c79afe333ea',
    messagingSenderId: '270620624991',
    projectId: 'login-c2782',
    storageBucket: 'login-c2782.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE_P-ZweCD00ayGmUQvF97ZA4uNrwyaRI',
    appId: '1:270620624991:ios:82955218a2bfdd26e333ea',
    messagingSenderId: '270620624991',
    projectId: 'login-c2782',
    storageBucket: 'login-c2782.firebasestorage.app',
    iosBundleId: 'com.example.groceryStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE_P-ZweCD00ayGmUQvF97ZA4uNrwyaRI',
    appId: '1:270620624991:ios:82955218a2bfdd26e333ea',
    messagingSenderId: '270620624991',
    projectId: 'login-c2782',
    storageBucket: 'login-c2782.firebasestorage.app',
    iosBundleId: 'com.example.groceryStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-TwTtVkDttO8o4Vr1xibPXkAKUZF1bKM',
    appId: '1:270620624991:web:a66f101a5ccaf1d8e333ea',
    messagingSenderId: '270620624991',
    projectId: 'login-c2782',
    authDomain: 'login-c2782.firebaseapp.com',
    storageBucket: 'login-c2782.firebasestorage.app',
  );

}